# Generated by Django 4.2.5 on 2023-09-18 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_remove_blogpost_views_alter_blogpost_author_and_more'),
        ('blog_app', '0004_blogpost_views'),
    ]

    operations = [
    ]
